version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: assets-webpack-plugin
    versions:
    - ">= 6.a, < 7"
  - dependency-name: copy-webpack-plugin
    versions:
    - ">= 6.a, < 7"
  - dependency-name: webpack-cli
    versions:
    - ">= 4.a, < 5"
  - dependency-name: "@babel/core"
    versions:
    - 7.13.8
  - dependency-name: css-loader
    versions:
    - 5.1.0
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
